import Searchbar from './components/Searchbar'
import Sidebar from './components/Sidebar'
import './globals.css'
import { Poppins, Source_Sans_3, Oswald } from 'next/font/google'

const poppins = Poppins({weight: "400",subsets: ['latin'] })
const oswald = Oswald({weight: "200",subsets: ['latin']})
const sans = Source_Sans_3({weight: "300",subsets: ['latin']})

export const metadata = {
  title: 'Admin Board - Mechanic Locator',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex'>
        <Sidebar className={oswald.className} />
        <main className={`${poppins.className} w-full h-full`}>
          <Searchbar />
          {children}
        </main>
      </body>
    </html>
  )
}
